;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;; AllScan.info products ;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;MENU:allscan-uci:simpleusb:*AllScan* UCI

;
; default [interface] settings for AllScan UCI products
;
[allscan-uci](!)
carrierfrom = usbinvert
clipledgpio = 1
ctcssfrom = no
deemphasis = no
legacyaudioscaling = no
plfilter = no
rxboost = no
rxmixerset = 650
txmixa = voice
txmixaset = 999
txmixb = no
txmixbset = 500

