;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;; HotSpotRadios.com products ;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;MENU:hotspotradio-pihat:simpleusb:*HotSpotRadio* PiHat
;MENU:hotspotradio-usb:simpleusb:*HotSpotRadio* HSR-USB
;MENU:hotspotradio-repeater:simpleusb:*HotSpotRadio* HSR-Repeater

;
; default [interface] settings for AllScan products (shared)
;
[hotspotradio-shared](!)
carrierfrom = usbinvert
ctcssfrom = no
deemphasis = no
invertptt = no
legacyaudioscaling = no
plfilter = yes
preemphasis = no
rxboost = yes
rxondelay = 0
txmixa = voice
txmixb = no
txoffdelay = 0

;
; default [interface] settings for HSR-PiHat
;
[hotspotradio-pihat](!,hotspotradio-shared)
rxmixerset = 200
txmixaset = 800
txmixbset = 0

;
; default [interface] settings for HSR-USB
;
[hotspotradio-usb](!,hotspotradio-shared)
rxmixerset = 300
txmixaset = 800
txmixbset = 0

;
; default [interface] settings for HSR-Repeater
;
[hotspotradio-repeater](!,hotspotradio-shared)
rxmixerset = 300
txmixaset = 800
txmixbset = 0

