;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;; SHARI (SA818 Ham Allstar Radio Interface) ;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;MENU:shari-pihat-pizero:simpleusb:*Kits4Hams* SHARI PiHat, PiZero
;MENU:shari-pixx:simpleusb:*Kits4Hams* SHARI PiXX

;
; default [interface] settings for AllScan products (shared)
;
[shari-shared](!)
carrierfrom = usbinvert
ctcssfrom = no
deemphasis = no
legacyaudioscaling = no
plfilter = no
preemphasis = no
rxboost = no
rxondelay = 0
txmixa = voice
txmixb = no
txoffdelay = 0

;
; default [interface] settings for SHARI PiHat, PiZero
;
[shari-pihat-pizero](!,shari-shared)
rxmixerset = 650
txmixaset = 600
txmixbset = 500

;
; default [interface] settings for SHARI PiXX
;
[shari-pixx](!,shari-shared)
rxmixerset = 650
txmixaset = 600
txmixbset = 500

