;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;; AIOC ;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;MENU:aioc:usbradio:*AIOC*

;
; default [node] settings for AIOC
;
[aioc](!)
carrierfrom = usbinvert
ctcssfrom = no
fever = 0
invertptt = no
legacyaudioscaling = no
rxboost = no
rxctcssadj = 0.500000
rxdemod = speaker
rxmixerset = 500
rxsqhyst = 500
rxsquelchadj = 500
rxvoiceadj = 0.500000
txctcssadj = 200
txmixaset = 500
txmixbset = 500
txprelim = no
txslimsp = 12000
