;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;; AllScan.info products ;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;MENU:allscan-uci:node,functions,duplex=3,rxchannel=SimpleUSB:*AllScan* UCI

;
; default [node] settings for AllScan UCI products
;
[allscan-uci](!)
althangtime = 200                      ; Longer squelch tail
duplex = 3                             ; Full-duplex, do not repeat Rx audio to Tx audio
hangtime = 100                         ; Squelch tail hang time (in ms)
holdofftelem = 1                       ; Hold off telemetry when signal is present on receiver or from connected nodes
linkunkeyct =                          ; Prevent courtesy tones when connected
telemdefault = 0                       ; Prevent "node X connected to node Y" messages

;
; default [function] settings for AllScan UCI products
;
[functions-allscan-uci](!)
921 = cop,21                           ; Enable Parrot Mode
922 = cop,22                           ; Disable Parrot Mode

