;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;; HotSpotRadios.com products ;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;MENU:hotspotradio-pihat:events,duplex=1,rxchannel=SimpleUSB:*HotSpotRadio* PiHat
;MENU:hotspotradio-usb:events,duplex=1,rxchannel=SimpleUSB:*HotSpotRadio* HSR-USB
;MENU:hotspotradio-repeater:events,duplex=2,rxchannel=SimpleUSB:*HotSpotRadio* HSR-Repeater

;
; default [events] settings for HotSpotRadio products (shared)
;
[events-hotspotradio](!)

cop,62,GPIO4:1 = c|t|RPT_RXKEYED
cop,62,GPIO4:0 = c|f|RPT_RXKEYED

;
; default [events] settings for HSR-PiHat
;
[events-hotspotradio-pihat](!,events-hotspotradio)

;
; default [events] settings for HSR-USB
;
[events-hotspotradio-usb](!,events-hotspotradio)

;
; default [events] settings for HSR-Repeater
;
[events-hotspotradio-repeater](!,events-hotspotradio)

