;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;; Indicate TX activity in filesystem ;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;MENU:keyed-file:events:-DEMO- Indicate TX activity in filesystem

[events-keyed-file](!)

touch /tmp/RPT_TXKEYED = s|t|RPT_TXKEYED
rm -f /tmp/RPT_TXKEYED = s|f|RPT_TXKEYED

