;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;; Assert GPIO (pin 8) when keyed ;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;MENU:keyed-gpio8:events:Assert GPIO pin 8 when keyed (COS LED)

[events-keyed-gpio8](!)

cop,62,GPIO8:1 = c|t|RPT_RXKEYED
cop,62,GPIO8:0 = c|f|RPT_RXKEYED

