;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;; SHARI (SA818 Ham Allstar Radio Interface) ;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;MENU:shari-pihat-pizero:events,duplex=2,rxchannel=SimpleUSB:*Kits4Hams* SHARI PiHat, PiZero
;MENU:shari-pixx:events,duplex=2,rxchannel=SimpleUSB:*Kits4Hams* SHARI PiXX

;
; default [events] settings for SHARI products (shared)
;
[events-shari](!)

cop,62,GPIO4:1 = c|t|RPT_RXKEYED
cop,62,GPIO4:0 = c|f|RPT_RXKEYED

;
; default [events] settings for SHARI PiHat, PiZero
;
[events-shari-pihat-pizero](!,events-shari)

;
; default [events] settings for SHARI PiXX
;
[events-shari-pixx](!,events-shari)

