#!/bin/bash

# N4IRS 07/26/2017
# mod4whip N8THN 2018
#   release date 20180323-1
# Fixes by WD6AWP 3/8/2021
# Fixes by WA3WCO 2/01/2024
#   Now executes asl-backup-menu to do the work

/usr/sbin/asl-backup-menu backup
